import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Bot, User, Sparkles, ExternalLink, CreditCard, CheckCircle2, ShieldCheck } from 'lucide-react';

// Helper to check for payment links generated by Razorpay
function extractPaymentUrl(text) {
  if (!text) return null;
  // Match standard URLs or rzp.io links
  const urlMatch = text.match(/https?:\/\/(?:rzp\.io\/[^\s]+|api\.razorpay\.com\/[^\s]+|[^\s]+\/pay\/[^\s]+)/i);
  if (urlMatch) return urlMatch[0];
  // General URL fallback if it mentions payment
  if (text.toLowerCase().includes('payment') || text.toLowerCase().includes('pay')) {
    const generalMatch = text.match(/https?:\/\/[^\s]+/i);
    return generalMatch ? generalMatch[0] : null;
  }
  return null;
}

// Helper to check for zero-click autonomous payment completion
function isZeroClickPaid(text) {
  if (!text) return false;
  const t = text.toLowerCase();
  return (
    (t.includes('payment complete') || t.includes('debited autonomously') || t.includes('auto-pay mandate')) &&
    (t.includes('no action needed') || t.includes('pre-authorized') || t.includes('debited') || t.includes('order confirmed'))
  );
}

export default function MessageFeed({ messages = [], isLoading = false, messagesEndRef, onUpsellAdd }) {
  return (
    <div className="flex-1 overflow-y-auto px-4 py-8">
      <div className="max-w-3xl mx-auto space-y-6">
        {messages.map((msg, index) => {
          const isUser = msg.role === 'user';
          const paymentUrl = !isUser ? extractPaymentUrl(msg.content) : null;
          const msgUpsells = (!isUser && msg.upsellItems?.length) ? msg.upsellItems : [];

          return (
            <div key={index} className="space-y-2">
              <div
                className={`flex items-start space-x-3.5 ${
                  isUser ? 'justify-end' : 'justify-start'
                }`}
              >
                {/* Bot Avatar */}
                {!isUser && (
                  <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-violet-600 flex items-center justify-center text-white shrink-0 mt-1 shadow-md shadow-indigo-500/20">
                    <Bot className="w-4 h-4" />
                  </div>
                )}

                {/* Message Bubble */}
                <div
                  className={`px-5 py-3.5 md:px-6 md:py-4 rounded-2xl text-sm md:text-base leading-relaxed max-w-[85%] space-y-3 shadow-md ${
                    isUser
                      ? 'bg-indigo-600 text-white rounded-tr-sm shadow-indigo-900/20 font-medium'
                      : 'bg-slate-900/95 text-slate-200 border border-slate-800/80 rounded-tl-sm backdrop-blur-sm'
                  }`}
                >
                  {isUser ? (
                    <p className="whitespace-pre-wrap leading-relaxed">{msg.content}</p>
                  ) : (
                    <div className="space-y-2 text-slate-200 leading-relaxed font-normal text-sm md:text-base [&>ol]:list-decimal [&>ol]:pl-5 [&>ol]:space-y-1.5 [&>ul]:list-disc [&>ul]:pl-5 [&>ul]:space-y-1.5 [&_strong]:font-bold [&_strong]:text-white [&_p]:leading-relaxed">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {msg.content}
                      </ReactMarkdown>
                    </div>
                  )}

                  {/* In-Chat Payment CTA Button if payment URL is detected */}
                  {paymentUrl && (
                    <div className="pt-2 border-t border-slate-800">
                      <a
                        href={paymentUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-semibold text-xs md:text-sm shadow-lg shadow-emerald-500/20 transition-all transform hover:-translate-y-0.5 active:translate-y-0"
                      >
                        <CreditCard className="w-4 h-4" />
                        <span>Complete Payment on Razorpay</span>
                        <ExternalLink className="w-3.5 h-3.5 opacity-80" />
                      </a>
                    </div>
                  )}

                  {/* In-Chat Zero-Click Autonomous Debit Banner */}
                  {!isUser && isZeroClickPaid(msg.content) && (
                    <div className="pt-2 border-t border-slate-800/80">
                      <div className="p-3.5 rounded-xl bg-gradient-to-r from-emerald-950/80 to-teal-950/80 border border-emerald-500/40 text-emerald-200 shadow-md shadow-emerald-950/30 space-y-1.5">
                        <div className="flex items-center space-x-2 text-emerald-400 font-bold text-xs md:text-sm">
                          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                          <span>Autonomous Zero-Click Payment Executed</span>
                        </div>
                        <p className="text-[11px] md:text-xs text-emerald-300/80 leading-relaxed font-sans">
                          Pre-authorized via <strong>Razorpay UPI Autopay</strong>. Transaction verified against your per-tx limit and approved category whitelist.
                        </p>
                        <div className="flex flex-wrap gap-1.5 pt-1 text-[10px] font-mono text-emerald-400">
                          <span className="px-2 py-0.5 rounded bg-emerald-900/60 border border-emerald-500/30">MANDATE: UPI_AUTOPAY</span>
                          <span className="px-2 py-0.5 rounded bg-emerald-900/60 border border-emerald-500/30">SECURITY GATE: PASSED</span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* User Avatar */}
                {isUser && (
                  <div className="w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-slate-300 shrink-0 mt-1 shadow-sm">
                    <User className="w-4 h-4" />
                  </div>
                )}
              </div>

              {/* Upsell Pill Buttons — shown below bot messages */}
              {msgUpsells.length > 0 && (
                <div className="pl-11 flex flex-wrap gap-2">
                  <span className="w-full text-[11px] text-slate-500 font-medium mb-0.5">💡 Pairs well with:</span>
                  {msgUpsells
                    .filter(item => item && (item.title || item.variant_id))
                    .map((item, i) => {
                      const priceNum = parseFloat(item.price ?? item.price_inr ?? item.amount ?? 0);
                      const displayPrice = !isNaN(priceNum) && priceNum > 0
                        ? `₹${priceNum.toLocaleString('en-IN')}`
                        : '';
                      const displayTitle = item.title || item.name || `Item ${i + 1}`;
                      return (
                        <button
                          key={i}
                          onClick={() => onUpsellAdd && onUpsellAdd(item)}
                          className="group flex items-center space-x-2 px-3.5 py-2 rounded-xl bg-slate-800/80 border border-slate-700/70 hover:border-indigo-500/60 hover:bg-indigo-950/40 text-slate-300 hover:text-white text-xs font-medium transition-all duration-150 shadow-sm"
                          title={item.reason || displayTitle}
                        >
                          <span className="text-indigo-400 group-hover:text-indigo-300">＋</span>
                          <span>{displayTitle}</span>
                          {displayPrice && (
                            <span className="text-slate-500 group-hover:text-slate-300 font-mono">{displayPrice}</span>
                          )}
                        </button>
                      );
                    })}
                </div>
              )}
            </div>
          );
        })}

        {/* Loading / Agent Thinking State */}
        {isLoading && (
          <div className="flex items-start space-x-3.5 justify-start">
            <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-violet-600 flex items-center justify-center text-white shrink-0 shadow-sm animate-pulse">
              <Sparkles className="w-4 h-4" />
            </div>
            <div className="bg-slate-900/90 border border-slate-800/80 px-4 py-3 rounded-2xl rounded-tl-sm flex items-center space-x-2 shadow-sm">
              <span className="text-xs text-slate-400 mr-1">Agent reasoning</span>
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce" />
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce [animation-delay:0.2s]" />
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce [animation-delay:0.4s]" />
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>
    </div>
  );
}
